const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/profile/me",
    heartbeat: "/auth/heartbeat",
    otpRequest: "/auth/otp/request",
    otpVerify: "/auth/otp/verify",
    resetPassword: "/auth/reset-password",
    forgotPassword: "/auth/forgot-password",
  },
  admin: {
    stats: "/admin/dashboard/stats",
    overview: "/admin/dashboard/overview",
    users: "/admin/users",
    students: "/admin/students",
    instructors: "/admin/instructors",
    courses: "/admin/courses",
    exams: "/admin/exams",
    enrollments: "/admin/enrollments",
    financials: "/admin/financials",
    coupons: "/admin/coupons",
    certificates: "/admin/certificates",
    downloadCertificate: (id) => `/admin/certificates/${id}/download`,
    payouts: "/admin/payouts",
    cms: "/admin/cms",
    settings: "/admin/settings",
    sections: "/admin/sections",
    auditLogs: "/admin/audit-logs",
    roles: "/admin/roles",
    permissions: "/admin/roles/permissions",
    subscriptions: "/admin/subscriptions",
    reviewQueue: "/admin/courses/review-queue",
    tickets: "/admin/tickets",
    qna: "/admin/qna",
    categories: "/admin/categories",
    resources: "/admin/resources",
    reviews: "/admin/reviews",
    vdocipherStatus: "/admin/vdocipher/status",
    vdocipherVideos: "/admin/vdocipher/videos",
    courseStaff: (courseId) => `/admin/courses/${courseId}/staff`,
    courseSubmitReview: (courseId) => `/admin/courses/${courseId}/submit-review`,
    courseApprove: (courseId) => `/admin/courses/${courseId}/approve`,
    courseReject: (courseId) => `/admin/courses/${courseId}/reject`,
    userSessions: (userId) => `/admin/users/${userId}/sessions`,
    userDevices: (userId) => `/admin/users/${userId}/devices`,
    userPermissions: (userId) => `/admin/users/${userId}/permissions`,
    forceLogout: (userId) => `/admin/users/${userId}/sessions`,
    payoutPaid: (payoutId) => `/admin/payouts/${payoutId}/paid`,
    instructorCommission: (instructorId) => `/admin/instructors/${instructorId}/commission`,
    events: "/admin/events",
    eventDetail: (id) => `/admin/events/${id}`,
    flashcards: "/admin/flashcards",
    instructorApplications: "/admin/instructor-applications",
    instructorApplication: (id) => `/admin/instructor-applications/${id}`,
    paymentApprove: (id) => `/admin/financials/payments/${id}/approve`,
    paymentReject: (id) => `/admin/financials/payments/${id}/reject`,
  },
  instructorDashboard: {
    overview: "/instructor/dashboard/overview",
  },
  instructor: {
    classes: "/instructor/classes",
    courses: "/instructor/courses",
    students: "/instructor/students",
    performance: "/instructor/performance",
    availability: "/instructor/availability",
    exams: "/instructor/exams",
    wallet: "/instructor/wallet",
    qna: "/instructor",
  },
  student: {
    qna: "/student",
    myCourses: "/student/courses/my-courses",
    financialsMyCourses: "/student/financials/my-courses",
    financialsCheckoutCourse: (courseId) => `/student/financials/checkout/course/${courseId}`,
    financialsCheckoutPackage: (packageId) => `/student/financials/checkout/package/${packageId}`,
    financialsPaymentProof: "/student/financials/payment-proof",
    financialsCheckoutPrivate: (availabilityId) => `/student/financials/checkout/private/${availabilityId}`,
    courseUnits: (courseId) => `/student/courses/${courseId}/units`,
    exams: "/student/exams",
    exam: (examId) => `/student/exams/${examId}`,
    examStart: (examId) => `/student/exams/${examId}/start`,
    examSubmit: (examId) => `/student/exams/${examId}/submit`,
    examResults: (examId, submissionId) => `/student/exams/${examId}/results/${submissionId}`,
    progressCompletedLessons: (courseId) => `/student/progress/courses/${courseId}/completed-lessons`,
    progressStats: (courseId) => `/student/progress/courses/${courseId}/stats`,
    progressResume: (courseId) => `/student/progress/courses/${courseId}/resume`,
    progressLessonAccess: (lessonId) => `/student/progress/lessons/${lessonId}/access`,
    progressLessonComplete: (lessonId) => `/student/progress/lessons/${lessonId}/complete`,
    lessonResources: (lessonId) => `/student/lessons/${lessonId}/resources`,
    lessonPlayback: (lessonId) => `/student/lessons/${lessonId}/playback`,
    bookingsAvailable: "/student/bookings/available-slots",
    bookSlot: (availabilityId) => `/student/bookings/${availabilityId}/book`,
    classes: "/student/classes",
    couponValidate: "/student/coupons/validate",
    recordings: "/student/recordings",
    recordingDetail: (sourceType, id) => `/student/recordings/${sourceType}/${id}`,
    recordingNotes: (sourceType, id) => `/student/recordings/${sourceType}/${id}/notes`,
    recordingNote: (sourceType, id, noteId) => `/student/recordings/${sourceType}/${id}/notes/${noteId}`,
    certificates: "/student/certificates",
    downloadCertificate: (id) => `/student/certificates/${id}/download`,
    claimCertificate: (courseId) => `/student/courses/${courseId}/certificates/claim`,
    myPayments: "/student/financials/my-payments",
    tickets: "/student/tickets",
    ticketReply: (id) => `/student/tickets/${id}/message`,
    wishlist: "/student/wishlist",
    wishlistItem: (courseId) => `/student/wishlist/${courseId}`,
    flashcards: "/student/flashcards",
    studyPlans: "/student/study-plans",
    studyPlan: (planId) => `/student/study-plans/${planId}`,
    studyPlanItems: (planId) => `/student/study-plans/${planId}/items`,
    studyPlanItem: (planId, itemId) => `/student/study-plans/${planId}/items/${itemId}`,
    myQuestions: "/student/questions",
    lessonQuestions: (lessonId) => `/student/lessons/${lessonId}/questions`,
    questionAnswers: (questionId) => `/student/questions/${questionId}/answers`,
    courseReviews: (courseId) => `/courses/${courseId}/reviews`,
  },
  notifications: "/notifications",
  public: {
    courses: "/courses",
    instructors: "/instructors",
    instructor: (id) => `/instructors/${id}`,
    instructorCourses: (id) => `/instructors/${id}/courses`,
    instructorReviews: (id) => `/instructors/${id}/reviews`,
    instructorSlots: (id) => `/instructors/${id}/slots`,
    packages: "/packages",
    posts: "/public/posts",
    banners: "/public/banners",
    post: (slug) => `/public/posts/${encodeURIComponent(slug)}`,
    siteSettings: "/public/settings",
    verifyCertificate: (serial) => `/certificates/verify/${encodeURIComponent(serial)}`,
    downloadCertificateBySerial: (serial) => `/certificates/verify/${encodeURIComponent(serial)}/download`,
    events: "/public/events",
    eventDetail: (id) => `/public/events/${id}`,
    instructorApplications: "/public/instructor-applications",
  },
};

export default endpoints;
